config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:get]
  authenticated :user do
    root 'portfolios#edit', as: :authenticated
  end
  resources :portfolios, only: [:index, :edit]
  get 'portfolio/:id' => 'portfolios#show', defaults: {format: 'json'}
  match 'portfolio/:id' => 'portfolios#update', via: [:put, :patch], defaults: {format: 'json'}
  get "/portfolios/*path" => 'portfolios#index'
  root 'welcome#index'
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  belongs_to :user
  has_many :projects, dependent: :destroy
  has_many :skills, dependent: :destroy

  accepts_nested_attributes_for :projects, reject_if: :invalid_project, allow_destroy: true
  accepts_nested_attributes_for :skills, reject_if: :invalid_skill, allow_destroy: true

  private

  def invalid_project(attrs)
    attrs[:name].blank? || attrs[:name] == "New Project" || attrs[:description].blank? || attrs[:features].blank?
  end

  def invalid_skill(attrs)
    attrs[:name].blank? || attrs[:name] == "New Skill"
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :portfolio
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :portfolio
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :portfolio, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  layout 'portfolio'
  def index
  end
  def show
    portfolio = Portfolio.find(params[:id])
    respond_to do |format|
      format.json { render json: portfolio.as_json({except: [:created_at, :update_at, :user_id], include: [{projects: {except: [:created_at, :updated_at, :portfolio_id]}}, {skills: {except: [:created_at, :updated_at, :portfolio_id]}}]}) }
    end
  end

  def edit
    portfolio = current_user.portfolio
    skills = portfolio.skills
    projects = portfolio.projects
    @portfolio = portfolio.to_json({except: [:created_at, :updated_at, :user_id], include: [{projects: {except: [:created_at, :updated_at, :portfolio_id]}}, {skills: {except: [:created_at, :updated_at, :portfolio_id]}}]})
  end

  def update
    portfolio = Portfolio.find(params[:id])
    if portfolio.update(portfolio_params)
      respond_to do |format|
        format.json { render json: portfolio.to_json({except: [:created_at, :updated_at, :user_id], include: [{projects: {except: [:created_at, :updated_at, :portfolio_id]}}, {skills: {except: [:created_at, :updated_at, :portfolio_id]}}]}), status: 200 }
      end
    else
      respond_to do |format|
        format.json {render json: {}.to_json, status: :unprocessable_entity}
      end
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:full_name, :bio, projects_attributes: [:id, :name, :description, :features, :_destroy], skills_attributes: [:id, :name, :_destroy])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_action :authenticate_user!

  def new
  end

  def update
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_action :authenticate_user!
  def new
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only [:edit]
  layout 'portfolio'
  def show
  end
  def edit
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<div class="flash">
  <% if notice.present? %>
    <aside class="alert alert-info">
      <%= notice %>
      <button type="button" class="close alert-close">&times;</button>
    </aside>
  <% elsif alert.present? %>
    <aside class="alert alert-danger">
      <%= alert %>
      <button type="button" class="close alert-close">&times;</button>
    </aside>
  <% end %>
  <script type="text/javascript">
    (function () {
      var alertCloseElems = document.getElementsByClassName("alert-close");
      if (alertCloseElems !== []){
        for (var i = 0; i < alertCloseElems.length; i++) {
          alertCloseElems[i].addEventListener("click", function () {
            var elemToRemove = this.parentElement;
            elemToRemove.parentElement.removeChild(elemToRemove);
          });
        }
      }
    })();
  </script>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <section class="navbar-header">
      <%= link_to "Portfolio Generator", root_path, class: "navbar-brand" %>
    </section>
    <ul class="nav navbar-nav navbar-right">
      <% unless user_signed_in? %>
        <li>
          <%= link_to "Sign In", new_user_session_path %>
        </li>
        <li>
          <%= link_to "Register", new_user_registration_path %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path%>
        </li>
        <li>
          <%= link_to "Edit Portfolio", authenticated_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF8" http-equiv="Content-Type">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PortfolioGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <div class="container flash-container">
    <%= render 'layouts/messages' %>
  </div>

  <%= yield %>

</body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
<head>
  <base href="/portfolios/"/>
  <meta content="text/html; charset=UTF8" http-equiv="Content-Type">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PortfolioGenerator</title>
  <%= stylesheet_link_tag    'portfolio', media: 'all' %>
  <%= javascript_include_tag 'portfolio' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <div class="container flash-container">
    <%= render 'layouts/messages' %>
  </div>

  <%= yield %>

</body>
</html>

app/views/portfolios/edit.html.erb
<article ng-app="edit">
  <%= content_tag 'div','ng-controller'=>'PortfolioEditCtrl', 'ng-init'=>"portfolio=#{@portfolio}" do %>
    <section class="container-fluid portfolio-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-5 jumbotron">
            <h1 ng-hide="fullNameEdit">
              <span class="glyphicon glyphicon-user"></span>
              {{ portfolio.full_name }}
            </h1>
            <h1 ng-show="fullNameEdit">
              <input type="text" name="fullName" ng-model="portfolio.full_name" class="form-control">
            </h1>
            <button type="button" ng-click="fullNameEdit=!fullNameEdit" class="btn btn-default btn-small edit">
              <span class="glyphicon glyphicon-edit"></span>
            </button>
          </div>
          <div class="col-md-6 col-md-offset-1 bio-skills">
            <button type="button" class="edit btn btn-default" ng-click="bioSkillsEdit=!bioSkillsEdit">
              <span class="glyphicon glyphicon-edit"></span>
            </button>
            <div ng-hide="bioSkillsEdit">
              <h2 class="portfolio-bio">
                {{ portfolio.bio}}
              </h2>
              <h4>
                <span ng-class="['label', {'label-primary': !skill._destroy}, {'label-danger': skill._destroy}]" ng-repeat="skill in skills">{{skill.name }}</span>
                <span class="label label-default new-skill" ng-click="newSkill()"><span class="glyphicon glyphicon-plus-sign"></span> New Skill</span>
              </h4>
            </div>
            <div ng-show="bioSkillsEdit">
              <div class="form-group form-group-lg">
                <input type="text" name="bio" ng-model="portfolio.bio" class="form-control">
              </div>
            </br>
              <form class="form-inline">
                <label for="skills">Skills:</label>
                <div class="input-group" ng-repeat="skill in skills track by $index">
                  <span ng-class="['input-group-addon', {'mark-delete': !skill._destroy}]" title="Mark for deletion (upon save)" ng-click="markDelete(skill)"><span ng-class="['glyphicon', {'glyphicon-remove': !skill._destroy}, {'glyphicon-refresh': skill._destroy}]"></span></span>
                  <input type="text" name="skill" class="form-control"  ng-model="skill.name">
                </div>
              </form>
            </div>
          </div>
        </div>
        <button type="button" class="save btn btn-primary" ng-click="saveChanges()">Save Changes</button>
      </div>
    </section>
    <section class="container projects">
      <div class="row project-window">
        <div class="col-md-3 project-list">
          <a ng-class="['project-list-item', {'marked-delete': project._destroy}]" ng-click="changeProject(project.id)" ng-repeat="project in projects">{{ project.name}}</a>
          <a class="project-list-item new-project" ng-click="newProject()" ><span class="glyphicon glyphicon-plus-sign"></span> New Project</a>
        </div>
        <div class="col-md-7 col-md-offset-1 project-content">
          <button type="button" class="btn btn-default edit" ng-click="projectEdit=!projectEdit">
            <span class="glyphicon glyphicon-edit"></span>
          </button>
          <div ng-hide="projectEdit">
            <section class="row clearfix project-title">
              <div class="blocky pull-left">
              </div>
              <h1>{{ project.name }}</h1>
              <h4>{{ project.description }}</h4>
            </section>
            <div id="project-features">
            </div>
          </div>
          <div ng-show="projectEdit">
            <section class="row clearfix project-title">
              <label for="name">Name:</label>
              <div class="input-group input-group-lg">
                <input type="text" name="name" ng-model="project.name" class="form-control">
                <span ng-class="['input-group-addon', {'mark-delete': !project._destroy}]" title="Mark for deletion (upon save)" ng-click="markDelete(project)"><span ng-class="['glyphicon', {'glyphicon-remove': !project._destroy}, {'glyphicon-refresh': project._destroy}]"></span></span>
              </div>
              <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" name="description" ng-model="project.description" class="form-control">
              </div>
            </section>
            <p>
              <label for="features">Features:</label>
              <textarea name="features" rows="8" ng-model="project.features" class="form-control"></textarea>
            </p>
          </div>
          <button type="button" class="save btn btn-primary" ng-click="saveChanges()">Save Changes</button>
        </div>
      </div>
    </section>
  <% end %>
</article>

app/views/portfolios/index.html.erb
<article ng-app="portfolios">
  <ng-view></ng-view>
</article>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>
      Portfolio Generator
    </h1>
    <p>Showcase your work in a well-crafted, public portfolio.
      </br>
      Simpy create an account, upload your projects, and show the world.
    </p>
    <%= link_to "Sign In", new_user_session_path, class: "btn btn-default" %>
    or 
    <%= link_to "Register Now", new_user_registration_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="container">
  <article class="row">
    <section class="col-md-4 info">
      <h1><span class="glyphicon glyphicon-folder-open"></span></h1>
      <h3>Start Your Portfolio</h3>
      <p>
        After registering for an account, you will begin working on your portfolio by providing a small bio about yourself.
      </p>
    </section>
    <section class="col-md-4 info">
      <h1><span class="glyphicon glyphicon-cloud-upload"></span></h1>
      <h3>Add Projects</h3>
      <p>
        Upload an image and add relevant information about all of your projects by filling out a simple form for each one.
      </p>
    </section>
    <section class="col-md-4 info">
      <h1><span class="glyphicon glyphicon-tags"></span></h1>
      <h3>Tag Your Skills</h3>
      <p>
        Complete your portfolio by adding tags for the skills you possess and technologies you work with. These tags are searchable so other users may search for portfolios by skillset.
      </p>
    </section>
  </article>
</div>